### PR TITLE
Unify Curve25519 key material

### PR DESCRIPTION
**Pull request by limeburst**
Since we are using the same key material for signing and key exchange, unifying them makes sense.

This change introduces dependency to lumi-im/elliptic.

### CODE REVIEW

**Comment by twittner** [comment]
Thank you for your pull request. After reading through the proposed changes I see the following problems:

1. It introduces another dependency.
2. Every `SecretKey::sign` calls `rand_bytes` which allocates another (temporary) vector and costs a system call.
3. The elliptic library is licensed under GPLv3 terms which would require us to also use the GPLv3.

If possible we would prefer to only depend on libsodium. Finally, the cost of Ed25519 wasn't measurable in benchmarks compared to using Curve25519 directly.

**Comment by limeburst** [comment]
Thank you for reviewing my pull request!

Regarding `SecretKey::sign` calling `rand_bytes` and costing a system call, I think this can be relieved by using secret-prefix SHA-512 as our PRF(conjectured to have no loss of security in the [Ed25519 paper](http://ed25519.cr.yp.to/ed25519-20110926.pdf)). This can be done inside elliptic.

Although this change introduces another dependency, I did it in hopes that it would make proteus' codebase easier to comprehend, and reduce some possible source of confusion. I am actually planning to relicense elliptic to a more permissive license, or release it into the public domain.

**Comment by twittner** [comment]
Thanks, I appreciate your motivation. However if we wanted to use Curve25519 directly we could already do so with libsodium. It even seems that agl/curve25519-donna (which your elliptic library uses) is itself [advising](https://github.com/agl/curve25519-donna/blob/f7837adf95a2c2dcc36233cb02a1fb34081c0c4a/README.md) to use NaCl or libsodium instead.

The original motivation to go with Ed25519 was that if we start with this key format we could easily use it for signing too if necessary. I understand that we can achieve signing from Curve25519 as well but since we already went the other way there seems to be little benefit in introducing a breaking change for equivalent functionality.

**Comment by limeburst** [comment]
Thank you for your valuable input!

**Pull request closed without merging**
